# Generated by Django 4.1.1 on 2022-09-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="class_section",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.class",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="guardians",
            field=models.ManyToManyField(
                blank=True, related_name="wards", to="students.guardian"
            ),
        ),
    ]
