# Generated by Django 4.1.1 on 2022-11-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_class_section_alter_student_guardians"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="class_roll_id",
        ),
        migrations.RemoveField(
            model_name="student",
            name="guardians",
        ),
        migrations.AddField(
            model_name="student",
            name="father",
            field=models.CharField(blank=True, max_length=300, verbose_name="father"),
        ),
        migrations.AddField(
            model_name="student",
            name="mother",
            field=models.CharField(blank=True, max_length=300, verbose_name="mother"),
        ),
    ]
