# Generated by Django 4.1.1 on 2022-09-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classname",
                    models.CharField(max_length=10, verbose_name="class name"),
                ),
                ("section", models.CharField(max_length=10, verbose_name="section")),
            ],
        ),
        migrations.AddConstraint(
            model_name="class",
            constraint=models.UniqueConstraint(
                fields=("classname", "section"), name="class_unique_constraint"
            ),
        ),
    ]
